version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@salesforce/ui-bundle-template-app-react-sample-b2e"
      - dependency-name: "@salesforce/ui-bundle-template-app-react-sample-b2x"
      - dependency-name: "@salesforce/webapp-template-app-react-sample-b2e-experimental"
      - dependency-name: "@salesforce/webapp-template-app-react-sample-b2x-experimental"

  - package-ecosystem: "npm"
    directory: "/samples/ui-bundle-template-app-react-sample-b2e"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/samples/ui-bundle-template-app-react-sample-b2x"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/samples/webapp-template-app-react-sample-b2e-experimental"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/samples/webapp-template-app-react-sample-b2x-experimental"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/samples/native-mobile-rental-tenant-app"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
